# Generated by Django 3.1.6 on 2021-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='clg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
